spring.jpa.hibernate.ddl-auto=update
logging.level.root=ERROR

# Clerk (use env variables)
clerk.jwks.url=${CLERK_JWKS_URL}
clerk.secret.key=${CLERK_SECRET_KEY}

# CORS (frontend URL)
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# File uploads
app.payment.upload-dir=${PAYMENT_UPLOAD_DIR}