spring.application.name=skillmentor

# Active profile (change if needed)
spring.profiles.active=prod

# Server port (Render/AWS compatible)
server.port=${PORT:8080}

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Use ONLY environment variables (no hardcoding)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}