name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Build Jar
      run: ./mvnw clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skillmentor-backend:latest .

    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillmentor-backend:latest

    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop skillmentor-backend || true
          docker rm skillmentor-backend || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/skillmentor-backend:latest
          docker run -d \
            --name skillmentor-backend \
            -p 8080:8080 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e CLERK_JWKS_URL=${{ secrets.CLERK_JWKS_URL }} \
            -e CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
            -e CORS_ALLOWED_ORIGINS="${{ secrets.CORS_ALLOWED_ORIGINS }}" \
            -e PAYMENT_UPLOAD_DIR=${{ secrets.PAYMENT_UPLOAD_DIR }} \
            -e PORT=${{ secrets.PORT }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/skillmentor-backend:latest
    
    
